# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/listComments
Accept: application/json

###

POST http://localhost:8080/saveUser
Content-Type: application/json

{
  "username": "junjae",
  "email": "baebo0823@naver.com"
}

###

GET http://localhost:8080/listUser
Accept: application/json

###

GET http://localhost:8080/findUser/1
Accept: application/json

###
PUT http://localhost:8080/updateUser
Content-Type: application/json

{
  "id": "5",
  "username": "1223adsf",
  "email": "sdrsdr@naver.com"
}

###
DELETE  http://localhost:8080/deleteUser/1
Accept: application/json

###
GET http://localhost:8080/findCommentById/2
Accept: application/json

###
GET http://localhost:8080/listByUserId/1
Accept: application/json

###
POST http://localhost:8080/saveComment
Content-Type: application/json

{
  "userId": 1,
  "content": "12"
}

###

